# Generated by Django 3.1.3 on 2022-01-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aurhor_name',
            field=models.CharField(blank=True, default='Unknown User', max_length=100),
        ),
    ]
