# Generated by Django 3.1.3 on 2022-01-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220129_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='aurhor_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='Unknown User', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.author'),
        ),
    ]
