# Generated by Django 3.1.3 on 2022-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220130_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_link',
            field=models.URLField(default='blog/image1.jpg', max_length=300),
        ),
    ]
