# Generated by Django 3.1.3 on 2022-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220201_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='image1.jpg', upload_to=''),
        ),
    ]
