# Generated by Django 3.1.3 on 2022-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(default='ty', max_length=25),
        ),
    ]
